GET http://localhost:3000/booksapi/json/

###

POST http://localhost:3000/booksapi/addUser
Content-Type: application/json

{
  "username": "Bruno",
  "email" : "bruno@bruno.com",
  "password": "password"
}
