POST http://localhost:3000/booksapi/user/adduser
Content-Type: application/json

{
  "username": "Brunos",
  "email" : "bru@email.com",
  "password": "123"
}

###

POST http://localhost:3000/booksapi/user/login
Content-Type: application/json

{
  "username": "Brunos",
  "email" : "bru@email.com",
  "password": "123"
}

###

GET http://localhost:3000/booksapi/books/all
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.QnJ1bm9z.WR9paOKGagRirWXoLS7thpPP_IiwFNQOI4nyVWwHQY4


###

POST http://localhost:3000/booksapi/books/add
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.QnJ1bm8x.dlB0UozojUGvu9-LwXPHWUuCaFzbeAh3OKWREPlo3KQ
Content-Type: application/json

{
  "book": {
    "title" : "aaa",
    "description" : "Aprendiz"
  }
}


###

DELETE http://localhost:3000/booksapi/books/delete
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.QnJ1bm8x.dlB0UozojUGvu9-LwXPHWUuCaFzbeAh3OKWREPlo3KQ
Content-Type: application/json

{
  "_id" : "602e6c860c430c1e445576fa"
}

###

PATCH http://localhost:3000/booksapi/books/update
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.QnJ1bm8x.dlB0UozojUGvu9-LwXPHWUuCaFzbeAh3OKWREPlo3KQ
Content-Type: application/json

{
  "book": {
    "_id" : "602e5e674ed10719e4f21eeb",
    "title" : "Conjurador",
    "description" : "Inquisicao"
  }
}

###