POST http://localhost:3300/booksapi/user/adduser
Content-Type: application/json

{
  "username": "Bruno1",
  "email" : "brn1@email.com",
  "password": "123"
}

###

POST http://localhost:3300/booksapi/user/login
Content-Type: application/json

{
  "username": "Bruno",
  "email" : "brn@email.com",
  "password": "123"
}

###

GET http://localhost:3300/booksapi/books/all
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.QnJ1bm8.TSl3HYo2YuYAItTrtJ3ZTm-_QUWY0bexzKix2br6dC4


###

POST http://localhost:3300/booksapi/books/add
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.QnJ1bm8.TSl3HYo2YuYAItTrtJ3ZTm-_QUWY0bexzKix2br6dC4
Content-Type: application/json

{
  "book": {
    "title" : "conjurador",
    "description" : "Aprendiz"
  }
}


###

DELETE http://localhost:3300/booksapi/books/delete
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.QnJ1bm8.TSl3HYo2YuYAItTrtJ3ZTm-_QUWY0bexzKix2br6dC4
Content-Type: application/json

{
  "_id" : "60fd69cd3b43c0104e506232"
}

###

PUT http://localhost:3300/booksapi/books/update
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.QnJ1bm8.TSl3HYo2YuYAItTrtJ3ZTm-_QUWY0bexzKix2br6dC4
Content-Type: application/json

{
  "book": {
    "_id" : "60fd6a693b43c0104e506233",
    "title" : "Conjurador",
    "description" : "Inquisicao"
  }
}

###